### PR TITLE
MedShapeNet and example

### PR DESCRIPTION
**Pull request by jdhenaos**
I have added MedShapeNet dataset, adding eight classes.

The next folders were ignored from MedShapeNet Dataset due to a lack of samples:

 ASOCA  (n=43)
AVT (n=45)
AutoImplantCraniotomy (n=14)
FaceVR  (n=14)

This Dataset requires a size number as a parameter to download the same number of samples per shape to ensure class balance.

MedShapeNet is not divided by train and test by default. Therefore, train data is downloaded from the first n required number of samples, and the test data is downloaded from the last n required number of samples.

dgcnn classification example was modified to use both ModelNet and MedShapeNet.

### CODE REVIEW

**Comment by puririshi98** [comment]
“MedShapeNet is not divided by train and test by default. Therefore, train data is downloaded from the first n required number of samples, and the test data is downloaded from the last n required number of samples.”
does this mean it is not doing a random split?


i would recommend the data be split randomly if train/val/test is not predefined

**Comment by puririshi98** [comment]
```
root@bldgs-dune-b00-mab-3:/workspace/pytorch_geometric# python3 examples/dgcnn_classification.py -h
Traceback (most recent call last):
  File "/workspace/pytorch_geometric/examples/dgcnn_classification.py", line 8, in <module>
    import torch_geometric.transforms as T
  File "/usr/local/lib/python3.12/dist-packages/torch_geometric/__init__.py", line 21, in <module>
    import torch_geometric.datasets
  File "/usr/local/lib/python3.12/dist-packages/torch_geometric/datasets/__init__.py", line 83, in <module>
    from .medshapenet import MedShapeNet
  File "/usr/local/lib/python3.12/dist-packages/torch_geometric/datasets/medshapenet.py", line 8, in <module>
    from MedShapeNet import MedShapeNet as msn
ModuleNotFoundError: No module named 'MedShapeNet'
root@bldgs-dune-b00-mab-3:/workspace/pytorch_geometric# pip install medshapenet
DEPRECATION: Loading egg at /usr/local/lib/python3.12/dist-packages/lightning_utilities-0.11.8-py3.12.egg is deprecated. pip 25.1 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /usr/local/lib/python3.12/dist-packages/faiss-1.7.4-py3.12.egg is deprecated. pip 25.1 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /usr/local/lib/python3.12/dist-packages/pyg_lib-0.4.0-py3.12-linux-aarch64.egg is deprecated. pip 25.1 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /usr/local/lib/python3.12/dist-packages/looseversion-1.3.0-py3.12.egg is deprecated. pip 25.1 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /usr/local/lib/python3.12/dist-packages/igraph-0.11.8-py3.12-linux-aarch64.egg is deprecated. pip 25.1 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /usr/local/lib/python3.12/dist-packages/lightning_thunder-0.2.0.dev0-py3.12.egg is deprecated. pip 25.1 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /usr/local/lib/python3.12/dist-packages/opt_einsum-3.4.0-py3.12.egg is deprecated. pip 25.1 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /usr/local/lib/python3.12/dist-packages/texttable-1.7.0-py3.12.egg is deprecated. pip 25.1 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at /usr/local/lib/python3.12/dist-packages/nvfuser-0.2.13a0+0d33366-py3.12-linux-aarch64.egg is deprecated. pip 25.1 will enforce this behaviour change. A possible replacement is to use pip for package installation. Discussion can be found at https://github.com/pypa/pip/issues/12330
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting medshapenet
  Downloading MedShapeNet-0.1.25-py3-none-any.whl.metadata (5.8 kB)
Collecting minio>=7.2.8 (from medshapenet)
  Downloading minio-7.2.12-py3-none-any.whl.metadata (6.5 kB)
Requirement already satisfied: tqdm>=4.66.5 in /usr/local/lib/python3.12/dist-packages (from medshapenet) (4.67.0)
Collecting numpy<1.26.0,>=1.18.5 (from medshapenet)
  Downloading numpy-1.25.2.tar.gz (10.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.8/10.8 MB 90.6 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      Traceback (most recent call last):
        File "/usr/local/lib/python3.12/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/local/lib/python3.12/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/local/lib/python3.12/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 112, in get_requires_for_build_wheel
          backend = _build_backend()
                    ^^^^^^^^^^^^^^^^
        File "/usr/local/lib/python3.12/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 77, in _build_backend
          obj = import_module(mod_path)
                ^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 995, in exec_module
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "/tmp/pip-build-env-51s0gzdh/overlay/local/lib/python3.12/dist-packages/setuptools/__init__.py", line 16, in <module>
          import setuptools.version
        File "/tmp/pip-build-env-51s0gzdh/overlay/local/lib/python3.12/dist-packages/setuptools/version.py", line 1, in <module>
          import pkg_resources
        File "/tmp/pip-build-env-51s0gzdh/overlay/local/lib/python3.12/dist-packages/pkg_resources/__init__.py", line 2172, in <module>
          register_finder(pkgutil.ImpImporter, find_on_path)
                          ^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

```

note that CI is also failing with this issue.
to fix CI see how the imports are done for webqsp: https://github.com/pyg-team/pytorch_geometric/blob/master/torch_geometric/datasets/web_qsp_dataset.py#L156-L157

however, I am having trouble installing medshapenet through pip to verify if your code actually works. Is that how you install it? could you provide your setup commands? based on this i will also advise wether those instructions should be included in your code somewhere (i will decide based on the complexity of the set up instructions)

**Comment by xnuohz** [comment]
Should it be `pip install MedShapeNet`?
https://github.com/GLARKI/MedShapeNet2.0

**Comment by jdhenaos** [comment]
Indeed,  `pip instal MedShapeNet` works.

The problem is that MedShapeNet uses a down-grade version of numpy. By default, it downloads version `1.25.2`, which works well with Python `3.10` but raises an error when recent versions like `3.12` are used. 

I'm not sure how to proceed with this conflict. Any hint you can give will be welcome.

**Comment by jdhenaos** [comment]
@xnuohz and @puririshi98 

I have talked with the MedShapeNet. Looks like they already solved the problem, I was able to run the Dataset on Python 3.10.12.

Please corroborate and let me know if there is some pending issue to solve

**Review by xnuohz — CHANGES_REQUESTED** [review]
left some comments:)

File: examples/dgcnn_classification.py [hunk 1]
```diff
@@ -1,22 +1,72 @@
...
+    test_dataset = ModelNet(root, '40', False, transform, pre_transform)
+elif args.dataset == 'medshapenet':
+    print('Loading training data')
+    train_dataset = MedShapeNet(root=root, size=50, split="train",
+                                pre_transform=pre_transform,
+                                transform=transform, force_reload=False)
+    print('Loading test data')
+    test_dataset = MedShapeNet(root=root, size=50, split="test",
+                               pre_transform=pre_transform,
+                               transform=transform, force_reload=False)
```
[the remark this answers is not in the document]
Comment (jdhenaos) [reply examples/dgcnn_classification.py:57]: Hi!

I am not sure of understanding correctly (lack of experience).

I took the class __init__ as equal as possible to the ModelNet dataset, with the addition of the"split" parameter which I took from WebQSPDataset. Could you please help me with more details about how should I proceed? Or do you have an example from PyG that I can use as a template?

If the training log is related to the CHANGELOG file, I will do it at last because of the constant change of the file regarding other accepted PRs. Otherwise, I am completely clueless and I would appreciate it if you could help me once again with some more details.

File: torch_geometric/datasets/medshapenet.py [hunk 2]
```diff
@@ -0,0 +1,167 @@
...
+        train_list, val_list, test_list = [], [], []
+        for dataset in list_of_datasets:
+            self.newpath = self.root + '/' + dataset.split("/")[1]
+            if not os.path.exists(self.newpath):
+                os.makedirs(self.newpath)
+            stl_files = msn_instance.dataset_files(dataset, '.stl')
+            stl_files = stl_files[:self.size]
+
+            train_data, val_data, test_data = random_split(
+                stl_files, [train_size, val_size, test_size])
```
[the remark this answers is not in the document]
Comment (jdhenaos) [reply torch_geometric/datasets/medshapenet.py:121]: Hi

MedShapeNet is not divided by "train", "test", and "validation" sets by default. Therefore, I added the random split to do it artificially. Is there another way to do it to return the sets when the "split" parameter is called? Do you know of any other dataset that has dealt with the same situation and I can use it as inspiration?

[the remark this answers is not in the document]
Comment (puririshi98) [reply torch_geometric/datasets/medshapenet.py:121]: u can use a frozen seed and then follow the patterns used by WebQSP dataset

File: examples/dgcnn_classification.py (hunk 1 above)
[the remark this answers is not in the document]
Comment (jdhenaos) [reply examples/dgcnn_classification.py:57]: @xnuohz could you please clarify your insights about this regard? I think this would be a minor task and we can get this project done quite soon

File: torch_geometric/datasets/medshapenet.py (hunk 2 above)
[the remark this answers is not in the document]
Comment (jdhenaos) [reply torch_geometric/datasets/medshapenet.py:121]: @xnuohz this dataset is not internally divided into training/test. That's why I internally divided manually. Otherwise, the dataset will be downloaded entirely into one variable and then divided into training/test externally just before to run the model training. 
Is that ok? If so, I will extract this piece of code and move it into the example script

[the remark this answers is not in the document]
Comment (xnuohz) [reply torch_geometric/datasets/medshapenet.py:121]: both are ok to me.
if there is no official splits provided, i prefer to move the split out of the dataset.

File: examples/dgcnn_classification.py (hunk 1 above)
[the remark this answers is not in the document]
Comment (xnuohz) [reply examples/dgcnn_classification.py:57]: sorry, at that time, my concern might be
```suggestion
    dataset = MedShapeNet(root, 50, pre_transform, transform)
    train_data, test_data = split(dataset)
```

**Comment by jdhenaos** [comment]
@xnuohz 

Thanks for your time checking the code and adding the last suggestions.

I have already worked in the suggested changes:

1. Now the whole dataset is loaded into a single variable.
2. Externally the dataset is divided into train and test. I used the random_split from torch with a fixed random seed to provide reproducibility in the dgcnn_classification example.

**Comment by xnuohz** [comment]
@jdhenaos thank you. can you share the train log?

File: examples/dgcnn_classification.py [hunk 3]
```diff
@@ -1,22 +1,86 @@
...
+        test_indices.extend(by_class[split_point:])
+
+    train_dataset = dataset[train_indices]
+    test_dataset = dataset[test_indices]
+
+else:
+    print('Loading training data')
+    train_dataset = ModelNet(root, '10', True, transform, pre_transform)
+    print('Loading test data')
+    test_dataset = ModelNet(root, '10', False, transform, pre_transform)
```
Comment (xnuohz) [inline examples/dgcnn_classification.py:76]:
```suggestion
elif args.dataset == 'modelnet10':
    print('Loading training data')
    train_dataset = ModelNet(root, '10', True, transform, pre_transform)
    print('Loading test data')
    test_dataset = ModelNet(root, '10', False, transform, pre_transform)
else:
    raise an error
```

File: torch_geometric/datasets/medshapenet.py [hunk 4]
```diff
@@ -0,0 +1,147 @@
...
+
+    @property
+    def raw_paths(self) -> List[str]:
+        r"""The absolute filepaths that must be present in order to skip
+        downloading.
+        """
+        if isinstance(self.raw_file_names, list):
+            return [osp.join(self.raw_dir, f) for f in self.raw_file_names]
+        else:
+            return [osp.join(self.raw_dir, self.raw_file_names)]
```
Comment (xnuohz) [inline torch_geometric/datasets/medshapenet.py:81]:
```suggestion
        return [osp.join(self.raw_dir, f) for f in self.raw_file_names]
```

**Review by xnuohz — COMMENTED** [review]
add an unit test if the dataset is small and easy to download

File: examples/dgcnn_classification.py (hunk 3 above)
Comment (jdhenaos) [reply examples/dgcnn_classification.py]: I have added the Error message:

```
~/Documents/projects$ python pytorch_geometric/examples/dgcnn_classification.py --dataset medsh > train.log
/home/juan/anaconda3/envs/pyg/lib/python3.11/site-packages/requests/__init__.py:86: RequestsDependencyWarning: Unable to find acceptable character detection dependency (chardet or charset_normalizer).
  warnings.warn(
usage: dgcnn_classification.py [-h]
                               [--dataset {modelnet10,modelnet40,medshapenet}]
                               [--dataset_dir DATASET_DIR]
                               [--batch_size BATCH_SIZE]
                               [--num_workers NUM_WORKERS] [--epochs EPOCHS]
dgcnn_classification.py: error: argument --dataset: invalid choice: 'medsh' (choose from 'modelnet10', 'modelnet40', 'medshapenet')
```

File: torch_geometric/datasets/medshapenet.py (hunk 4 above)
Comment (jdhenaos) [reply torch_geometric/datasets/medshapenet.py]: In addition, I have creaed a unitest as you suggested. This was the log:
```
~/Documents/projects$ pytest pytorch_geometric/test/datasets/test_medshapenet.py 
================================================================================= test session starts ==================================================================================
platform linux -- Python 3.11.11, pytest-8.3.5, pluggy-1.5.0 -- /home/juan/anaconda3/envs/pyg/bin/python3.11
cachedir: .pytest_cache
rootdir: /home/juan/Documents/projects/pytorch_geometric
configfile: pyproject.toml
plugins: anyio-4.9.0
collecting ... 
        This message only displays once when importing MedShapeNet for the first time.

        MedShapeNet API is under construction, more functionality will come soon!

        For information use MedShapeNet.msn_help().
        Alternatively, check the GitHub Page: https://github.com/GLARKI/MedShapeNet2.0

        PLEASE CITE US If you used MedShapeNet API for your (research) project:
        
        @article{li2023medshapenet,
        title={MedShapeNet--A Large-Scale Dataset of 3D Medical Shapes for Computer Vision},
        author={Li, Jianning and Pepe, Antonio and Gsaxner, Christina and Luijten, Gijs and Jin, Yuan and Ambigapathy, Narmada, and others},
        journal={arXiv preprint arXiv:2308.16139},
        year={2023}
        }

        PLEASE USE the def dataset_info(self, bucket_name: str) to find the proper citation alongside MedShapeNet when utilizing a dataset for your resarch project.
        
collected 1 item                                                                                                                                                                       

pytorch_geometric/test/datasets/test_medshapenet.py::test_medshapenet Connection to MinIO server successful.

Download directory created at: /home/juan/Documents/projects/msn_downloads
PASSED

=================================================================================== warnings summary ===================================================================================
../../anaconda3/envs/pyg/lib/python3.11/site-packages/requests/__init__.py:86
  /home/juan/anaconda3/envs/pyg/lib/python3.11/site-packages/requests/__init__.py:86: RequestsDependencyWarning: Unable to find acceptable character detection dependency (chardet or charset_normalizer).
    warnings.warn(

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
============================================================================ 1 passed, 1 warning in 41.82s =============================================================================
```

**Review by puririshi98 — APPROVED** [review]
lgtm will merge once CI passes

File: torch_geometric/datasets/medshapenet.py [hunk 5]
```diff
@@ -0,0 +1,144 @@
...
+            filter(
+                lambda x: x not in [
+                    'medshapenetcore/ASOCA', 'medshapenetcore/AVT',
+                    'medshapenetcore/AutoImplantCraniotomy',
+                    'medshapenetcore/FaceVR'
+                ], list_of_datasets))
+
+        subset = []
+        for dataset in list_of_datasets:
+            self.newpath = self.root + '/' + dataset.split("/")[1]
```
Comment (akihironitta) [inline torch_geometric/datasets/medshapenet.py:99]: I got to this PR while reviewing #10472. Does this work on Windows? Could we make it os-agnostic?

Comment (akihironitta) [reply torch_geometric/datasets/medshapenet.py:99]: cc @jdhenaos @puririshi98

Comment (jdhenaos) [reply torch_geometric/datasets/medshapenet.py:99]: Hi @akihironitta 

I'm sorry for not getting back to you sooner.

Is this still an open issue?
